services:
  java-app:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "1337"
    restart: always
    networks:
      - backend


  nginx:
    build:
      context: ./www
      dockerfile: Dockerfile.nginx
    ports:
      - "24598:24598"
    depends_on:
      - java-app
    networks:
      - backend

networks:
  backend: